# Generated by Django 5.2.6 on 2026-01-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_montant_transcription_filtrees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nature', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=200)),
                ('date_arrivee', models.DateField()),
                ('mois', models.CharField(max_length=20)),
                ('exercice', models.CharField(max_length=20)),
                ('nom_piece', models.CharField(max_length=200)),
                ('nom_poste', models.CharField(max_length=60)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'total_montant_transcription_filtrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_anomalie', models.DateField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('statut', models.CharField(max_length=15)),
                ('type_analyse', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.IntegerField(default=0)),
                ('poste', models.IntegerField(default=0)),
                ('rubrique', models.IntegerField(default=0)),
                ('numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('acte_reglementaire', models.CharField(default='', max_length=255)),
                ('solde_en_cours_exo', models.CharField(default='', max_length=35)),
                ('solde_fin_gest', models.CharField(default='', max_length=35)),
                ('type', models.CharField(max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='data.anomalie')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice', models.CharField(max_length=10, null=True)),
                ('mois', models.CharField(max_length=2, null=True)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('contenu', models.BinaryField()),
                ('date_arrivee', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('poste_comptable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_comptable_documents', to='users.poste_comptable')),
            ],
        ),
        migrations.AddField(
            model_name='anomalie',
            name='document',
            field=models.ManyToManyField(related_name='anomalies', to='data.document'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piece', models.CharField(max_length=10)),
                ('periode', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('poste_comptable', models.ManyToManyField(related_name='pieces', to='users.poste_comptable')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_documents', to='data.piece'),
        ),
        migrations.CreateModel(
            name='PieceCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_piece', to='data.compte')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_comptes', to='data.piece')),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='data.proprietaire'),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='data.compte')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data.document')),
            ],
        ),
    ]
