# Generated by Django 5.2.6 on 2025-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('contenu', models.BinaryField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
