# Generated by Django 5.2.6 on 2025-10-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='poste_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_comptable_documents', to='users.poste_comptable'),
        ),
        migrations.AddField(
            model_name='piece',
            name='poste_comptable',
            field=models.ManyToManyField(related_name='pieces', to='users.poste_comptable'),
        ),
        migrations.AddField(
            model_name='document',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_documents', to='data.piece'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='data.document'),
        ),
    ]
