# Generated by Django 5.2.6 on 2025-10-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='exercice',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mois',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
