# Generated by Django 5.2.6 on 2025-10-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_document_exercice_document_mois'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='mois',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='piece',
        ),
        migrations.AlterField(
            model_name='transcription',
            name='numero_compte',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
