# Generated by Django 5.2.6 on 2025-10-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_transcription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='data.document'),
        ),
    ]
