# Generated by Django 5.2.6 on 2025-10-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_transcription_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.IntegerField(default=0)),
                ('poste', models.IntegerField(default=0)),
                ('rubrique', models.IntegerField(default=0)),
                ('numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('acte_reglementaire', models.CharField(default='', max_length=255)),
                ('solde_en_cours_exo', models.CharField(default='', max_length=35)),
                ('solde_fin_gest', models.CharField(default='', max_length=35)),
                ('type', models.CharField(max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('proprietaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='data.proprietaire')),
            ],
        ),
    ]
