# Generated by Django 5.2.6 on 2025-10-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_proprietaire_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_piece', to='data.compte')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_comptes', to='data.piece')),
            ],
        ),
    ]
