# Generated by Django 5.2.6 on 2025-10-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_piececompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='piececompte',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='piececompte',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
