# Generated by Django 5.2.6 on 2025-10-20 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_piececompte_created_at_piececompte_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='numero_compte',
        ),
        migrations.AddField(
            model_name='transcription',
            name='compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='data.compte'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='data.document'),
        ),
    ]
