# Generated by Django 5.2.6 on 2025-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_transcription_numero_compte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piececompte',
            name='nature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
