# Generated by Django 5.2.6 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_piececompte_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='montant',
            field=models.FloatField(),
        ),
    ]
