# Generated by Django 5.2.6 on 2025-11-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
