# Generated by Django 5.2.6 on 2025-11-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_trace_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_anomalie', models.DateField()),
                ('statut', models.CharField(max_length=15)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomalie', to='data.document')),
            ],
        ),
    ]
