# Generated by Django 5.2.6 on 2025-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_anomalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
