# Generated by Django 5.2.6 on 2025-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_anomalie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
