# Generated by Django 5.2.6 on 2025-11-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_anomalie_created_at_anomalie_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_montant_transcription_filtrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=200)),
                ('mois', models.CharField(max_length=20)),
                ('exercice', models.CharField(max_length=20)),
                ('nom_piece', models.CharField(max_length=200)),
                ('nom_poste', models.CharField(max_length=60)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'total_montant_transcription_filtrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='data.anomalie')),
            ],
        ),
    ]
