# Generated by Django 5.2.6 on 2025-11-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_total_montant_transcription_filtrees_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='document',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='document',
            field=models.ManyToManyField(related_name='anomalies', to='data.document'),
        ),
    ]
