# Generated by Django 5.2.6 on 2025-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_remove_anomalie_document_anomalie_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
