# Generated by Django 5.2.6 on 2025-11-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_anomalie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalie',
            old_name='type',
            new_name='type_analyse',
        ),
    ]
