# Generated by Django 5.2.6 on 2025-11-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_rename_type_anomalie_type_analyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
