# Generated by Django 5.2.6 on 2025-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_transcription_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
