# Generated by Django 5.2.6 on 2025-12-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_document_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trace',
        ),
    ]
