# Generated by Django 5.2.6 on 2025-12-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_delete_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=5)),
            ],
        ),
    ]
