# Generated by Django 5.2.6 on 2025-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_exercice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='annee',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
