"""
Django settings for supervision project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(l13^2e3eviq#&_^2%sf5ls^#=!k)gso^7a2&06jolhqe)e9yt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'data.apps.DataConfig',
    'users.apps.UsersConfig',
    'audit.apps.AuditConfig',
    'evenement.apps.EvenementConfig',
    'corsheaders',
    'rest_framework',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # doit être en haut
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.CurrentUserMiddleware',
]

APPEND_SLASH = False

USE_TZ = True
TIME_ZONE = 'Indian/Antananarivo'


# # Pour autoriser le frontend React (CORS) LOCALE

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
# ]

# CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_ALL_ORIGINS = True # Pour tester


# # # ---- CSRF ----
# CSRF_COOKIE_HTTPONLY = False  # OBLIGATOIRE pour React
# CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_SECURE = False   # OK en local

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:3000",
# ]


# # # ---- Sessions ----
# SESSION_ENGINE = "django.contrib.sessions.backends.db"
# SESSION_COOKIE_NAME = "sessionid"
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SAMESITE = "Lax"
# SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_AGE = 60 * 60 * 24 * 14   # 2 semaines
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ***************************************************

# SETTINGS PROD
ALLOWED_HOSTS = [
    "192.168.1.236",
    "localhost",
    "127.0.0.1"
]
CORS_ALLOW_ALL_ORIGINS = True


CSRF_TRUSTED_ORIGINS = [
    "http://192.168.1.236"
]
CSRF_COOKIE_HTTPONLY = False  # OBLIGATOIRE pour React
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = False   # OK en local


SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14   # 2 semaines
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# **************************************************


# ---- Configuration Email ----
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "darcyfranklin14@gmail.com"
EMAIL_HOST_PASSWORD = "iefucprocksiofjq"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    # ],
}

# RECAPTCHA_SECRET_KEY = "6LeVF8srAAAAAEQBQ-2NnWOrU_rCgGp7RrESw7FF"

ROOT_URLCONF = 'supervision.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'supervision.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'supervision',
        'USER': 'supervision_user',
        'PASSWORD': 'passwordfort',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'supervision',
#         'USER': 'postgres',
#         'PASSWORD': 'admin',
#         'HOST': 'localhost',
#         'PORT': '5432'
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "users.Authentification"



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Dossier où collectstatic va mettre tous les fichiers statiques
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# URL pour accéder aux fichiers statiques
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
