# Generated by Django 5.2.6 on 2025-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date_action',
            field=models.DateField(auto_now_add=True),
        ),
    ]
