# Generated by Django 5.2.6 on 2025-12-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_date_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
