# Generated by Django 5.2.6 on 2025-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_date_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
