# Generated by Django 5.2.6 on 2025-12-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_document_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='document_filename',
        ),
    ]
