# Generated by Django 5.2.6 on 2025-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_remove_auditlog_document_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='document_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
