# Generated by Django 5.2.6 on 2025-10-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poste_comptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste_comptable', models.CharField(max_length=50)),
                ('prenom_poste_comptable', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=10)),
                ('categorie', models.CharField(max_length=20)),
                ('comptable', models.CharField(max_length=100)),
                ('comptable_rattachement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poste_rattaches', to='users.poste_comptable')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_comptables', to='users.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifiant', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentification', to='users.utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='users.zone'),
        ),
    ]
