# Generated by Django 5.2.6 on 2025-09-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
