# Generated by Django 5.2.6 on 2025-10-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste_comptable',
            old_name='nom_poste_comptable',
            new_name='lieu',
        ),
        migrations.RemoveField(
            model_name='poste_comptable',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='poste_comptable',
            name='comptable',
        ),
        migrations.RemoveField(
            model_name='poste_comptable',
            name='prenom_poste_comptable',
        ),
        migrations.RemoveField(
            model_name='poste_comptable',
            name='type',
        ),
        migrations.AddField(
            model_name='poste_comptable',
            name='code_poste',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='poste_comptable',
            name='nom_poste',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poste_comptable',
            name='poste',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='poste_comptable',
            name='responsable',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='poste_comptable',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_comptables', to='users.utilisateur'),
        ),
    ]
