# Generated by Django 5.2.6 on 2025-10-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_nom_poste_comptable_poste_comptable_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste_comptable',
            name='poste',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
