# Generated by Django 5.2.6 on 2025-10-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_poste_comptable_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='im',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='users.zone'),
        ),
    ]
