# Generated by Django 5.2.6 on 2025-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_utilisateur_im_alter_utilisateur_fonction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentification',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
