# Generated by Django 5.2.6 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_authentification_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
